# IMPORTANT: This file should be auto-generated by nixos-generate-config on zz2
# Run `nixos-generate-config` on the new laptop to get the correct hardware configuration
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  # Boot partition - UPDATE THIS for zz2
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];

  # Kernel modules - UPDATE THIS for zz2
  # zz2 has Intel CPU, so use kvm-intel
  boot.kernelModules = [ "kvm-intel" ];

  # File systems - UPDATE THESE UUIDs for zz2
  # Run `lsblk -f` or `blkid` on zz2 to get the correct UUIDs
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/CHANGE-ME-ROOT-UUID";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CHANGE-ME-BOOT-UUID";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Swap - UPDATE OR REMOVE for zz2
  # swapDevices = [
  #   { device = "/dev/disk/by-uuid/CHANGE-ME-SWAP-UUID"; }
  # ];

  # NixOS requires a stateVersion, do not change this
  # system.stateVersion = "26.05";
}
